#!/bin/bash

SSH_CMD="/usr/bin/ssh"
SSH_SOCKS_PORT=$1
SSH_USER=$2
SSH_SERVER=$3

echo "SSH_SOCKS_PORT = $SSH_SOCKS_PORT"
echo "SSH_USER = $SSH_USER"
echo "SSH_SERVER = $SSH_SERVER"

$SSH_CMD -D $SSH_SOCKS_PORT -N $SSH_USER@$SSH_SERVER
